### ISSUE TITLE
show Easynews & Furk links as 'Premium'

### ISSUE THREAD

**Issue by rich333** [a4k-openproject/script.module.openscrapers#146]
Currently Easynews & Furk results are treated as 'direct' sources by addons, this is a problem if using the 'use debrid only' filter (and possibly other sorting/filtering options).

Solution would be to consider these links 'premium' along with torrent/debrid rather than the 'free' links.

**Comment by 123Venom** [comment]
curious why turn on 'use debrid only' in an addon and then want non Premium links to show?  You could turn that option off and then turn off all free hosters and accomplish what you want.  Personally I do not use that option as a couple free hosters are worthy for hard to find older shows, like the episode/series only hosters.

**Comment by rich333** [comment]
I was under the assumption that the 'hosters' section has some providers that provide both free & debrid links (as opposed to 'debrid only'), so have not been turning them all off. 

Would be ideal if the filter allowed only premium links (torrents/debrid) + easynews/furk to show. the other free links do not work due to my location/network and always buffer. the problem is that to display easynews/furk all free links must also be displayed.

Another minor issue is the EN/Furk links do not stand out (white not colored) and blend in with the free links in the source list for casual users.

**Comment by Tikipeter** [comment]
@rich333 

Unfortunately, there is not much that can be done to fix this issue.

All these issues revolving around specific highlights, position in the results, and specific filtering etc for Furk/Easynews are all dependent on the add-on accessing Openscrapers, rather than openscrapers itself.

Openscrapers only returns the results for each scraper that is activated.

There could be a 'premium' key added to the Furk/Easynews results so add-ons could do something with that, but it is still up to the add-ons to implement the code to distinguish it in the results displayed.

I share your pain with this issue, but a fix will 99% have to come from the add-ons you use.
