### ISSUE TITLE
cloudflare is down again....

### ISSUE THREAD

**Issue by FalconEagleTest** [a4k-openproject/script.module.openscrapers#147]
hi,
first of all great addon, THANKS.
but i can see that the cloudflare is down again...
can you take alook?
thanks.

**Comment by bjgood** [comment]
I've got good news and bad news for you. The bad news is some of the sources that openscraper uses have and are switching to a new cloudflare version 2 approach. The good news is some of them are switching back to regular cloudflare because version 2 is too complicated and is scaring off visitors to the source site.
I personally felt this would happen after the first time I experienced cloudflare version 2.
Later...
